# Generated by Django 5.1.3 on 2024-12-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='account_number',
            field=models.PositiveIntegerField(default=True, unique=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.IntegerField(default=True),
        ),
    ]
