# Generated by Django 5.1.3 on 2024-12-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscription_account_number_subscription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
