# Generated by Django 5.1.3 on 2024-12-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_subscription_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
