# Generated by Django 5.1.3 on 2024-12-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_subscription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account_number',
            field=models.CharField(max_length=20, verbose_name='Account Number'),
        ),
    ]
